version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "vitest"
          - "@vitest/*"
          - "tsup"
          - "@biomejs/*"
          - "rimraf"
          - "turbo"

  - package-ecosystem: "npm"
    directory: "/packages/query-builder"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/esql-dsl"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/search-dsl"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
