#!/usr/bin/env bash

#
# Runs the client tests via Docker with the expectation that the required
# environment variables have already been exported before running this script.
#
# The required environment variables include:
#
#   - $ELASTICSEARCH_VERSION
#   - $NODE_JS_VERSION
#

set -eo pipefail

function cleanup {
  docker container rm --force --volumes elasticsearch-dsl-js > /dev/null 2>&1 || true
}

trap cleanup EXIT

# create client image
docker build \
  --file .ci/Dockerfile \
  --tag elastic/elasticsearch-dsl-js \
  --build-arg NODE_JS_VERSION=${NODE_JS_VERSION} \
  .

# run the client unit and oss integration test
docker run \
  --network=esnet-oss \
  --volume $repo:/usr/src/app \
  --volume /usr/src/app/node_modules \
  --name elasticsearch-dsl-js \
  --rm \
  elastic/elasticsearch-dsl-js \
  npm test
