name: docs-preview-cleanup
on:
  pull_request_target:
    types: [closed]
permissions:
  contents: none
  deployments: write
  id-token: write
jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@08a1e1a51c249fb0ee22730705ffaba1d6d3a7ef # v1
