name: docs-deploy
on:
  workflow_run:
    workflows: [docs-build]
    types: [completed]
permissions:
  contents: read
  deployments: write
  id-token: write
  pull-requests: write
  actions: read
jobs:
  deploy:
    uses: elastic/docs-actions/.github/workflows/docs-deploy.yml@08a1e1a51c249fb0ee22730705ffaba1d6d3a7ef # v1
    with:
      enable-vale-linting: true
