name: docs-build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  merge_group: ~
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@5b4c82c9c9e3b29f3d8c470b41ce6e17fabdad15 # v1
    with:
      enable-vale-linting: true
